{
 "title": "API metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Response Time 95th percentile, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "api.response.time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "api.calls.count",
     "query": "SELECT non_negative_derivative(sum(\"value\"), 1s) FROM \"duration_3d_precision_1s\".\"api.calls\" WHERE $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response time 95th percentile, ms",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "api.response.time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "range",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "api.calls.count",
     "query": "SELECT non_negative_derivative(sum(\"value\"), 1s) FROM \"duration_3d_precision_1s\".\"api.calls\" WHERE $timeFilter GROUP BY time(1s) fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repository call time, ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_repository.$tag_action",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "repository" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "api.repository.call",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}